
package com.eterra._public.services.data.historicaltrendprovider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.eterra._public.services.data.datatypes.AveragedDataRequest;
import com.eterra._public.services.data.datatypes.AveragedDataResponse;
import com.eterra._public.services.data.datatypes.ConfigurationResponse;
import com.eterra._public.services.data.datatypes.DataElementSettingsResponse;
import com.eterra._public.services.data.datatypes.FullResolutionDataRequest;
import com.eterra._public.services.data.datatypes.FullResolutionDataResponse;
import com.eterra._public.services.data.datatypes.MappingsResponse;
import com.eterra._public.services.data.datatypes.MeasurementBasedEventsRequest;
import com.eterra._public.services.data.datatypes.MeasurementBasedEventsResponse;
import com.eterra._public.services.data.datatypes.MeasurementBasedOverviewStateRequest;
import com.eterra._public.services.data.datatypes.MeasurementBasedOverviewStateResponse;
import com.eterra._public.services.data.datatypes.ModeSettingsResponse;
import com.eterra._public.services.data.datatypes.ObjectFactory;
import com.eterra._public.services.data.datatypes.PdxDataAndEventsRequest;
import com.eterra._public.services.data.datatypes.PdxDataAndEventsResponse;
import com.eterra._public.services.data.datatypes.PdxModeCentricDataRequest;
import com.eterra._public.services.data.datatypes.PdxModeCentricDataResponse;
import com.eterra._public.services.data.datatypes.PdxModeFilteredDataRequest;
import com.eterra._public.services.data.datatypes.PdxModeFilteredDataResponse;
import com.eterra._public.services.data.datatypes.PmuMinMaxDataRequest;
import com.eterra._public.services.data.datatypes.PmuMinMaxDataResponse;
import com.eterra._public.services.data.datatypes.ReferenceAngleRequest;
import com.eterra._public.services.data.datatypes.ReferenceAngleResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HistoricalTrendProvider", targetNamespace = "http://www.eterra.com/public/services/data/historicaltrendprovider")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HistoricalTrendProvider {


    /**
     * Gets min/max summary data for a set of PMU measurements
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.PmuMinMaxDataResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetPmuMinMaxData", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetPmuMinMaxData")
    @WebResult(name = "PmuMinMaxDataResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public PmuMinMaxDataResponse getPmuMinMaxData(
        @WebParam(name = "PmuMinMaxDataRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        PmuMinMaxDataRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets full resolution data for a set of PMU measurements
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.FullResolutionDataResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetFullResolutionData", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetFullResolutionData")
    @WebResult(name = "FullResolutionDataResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public FullResolutionDataResponse getFullResolutionData(
        @WebParam(name = "FullResolutionDataRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        FullResolutionDataRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets PDX mode filtered data for a set of PDX IDs
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.PdxModeFilteredDataResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetPdxModeFilteredData", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetPdxModeFilteredData")
    @WebResult(name = "PdxModeFilteredDataResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public PdxModeFilteredDataResponse getPdxModeFilteredData(
        @WebParam(name = "PdxModeFilteredDataRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        PdxModeFilteredDataRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets PDX mode centric data for a set of PDX mode centric IDs
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.PdxModeCentricDataResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetPdxModeCentricData", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetPdxModeCentricData")
    @WebResult(name = "PdxModeCentricDataResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public PdxModeCentricDataResponse getPdxModeCentricData(
        @WebParam(name = "PdxModeCentricDataRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        PdxModeCentricDataRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets one second averaged data for a set of substations and measurement types
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.AveragedDataResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetAveragedData", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetAveragedData")
    @WebResult(name = "AveragedDataResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public AveragedDataResponse getAveragedData(
        @WebParam(name = "AveragedDataRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        AveragedDataRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets events generated directly from measurement values (magnitude/wams/substation)
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.MeasurementBasedEventsResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetMeasurementBasedEvents", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetMeasurementBasedEvents")
    @WebResult(name = "MeasurementBasedEventsResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public MeasurementBasedEventsResponse getMeasurementBasedEvents(
        @WebParam(name = "MeasurementBasedEventsRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        MeasurementBasedEventsRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets overview state for all magnitude event types
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.MeasurementBasedOverviewStateResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetMeasurementBasedOverviewState", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetMeasurementBasedOverviewState")
    @WebResult(name = "MeasurementBasedOverviewStateResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public MeasurementBasedOverviewStateResponse getMeasurementBasedOverviewState(
        @WebParam(name = "MeasurementBasedOverviewStateRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        MeasurementBasedOverviewStateRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets reference angle measurement ID changes
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.ReferenceAngleResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetReferenceAngle", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetReferenceAngle")
    @WebResult(name = "ReferenceAngleResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public ReferenceAngleResponse getReferenceAngle(
        @WebParam(name = "ReferenceAngleRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        ReferenceAngleRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets all PDX related values and events
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.PdxDataAndEventsResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetPdxDataAndEvents", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetPdxDataAndEvents")
    @WebResult(name = "PdxDataAndEventsResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public PdxDataAndEventsResponse getPdxDataAndEvents(
        @WebParam(name = "PdxDataAndEventsRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        PdxDataAndEventsRequest parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets latest PDX mode band values
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.ModeSettingsResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetModeSettings", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetModeSettings")
    @WebResult(name = "ModeSettingsResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public ModeSettingsResponse getModeSettings(
        @WebParam(name = "ModeSettingsRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        Object parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets latest magnitude event limit values
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.DataElementSettingsResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetDataElementSettings", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetDataElementSettings")
    @WebResult(name = "DataElementSettingsResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public DataElementSettingsResponse getDataElementSettings(
        @WebParam(name = "DataElementSettingsRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        Object parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets latest measurement configuration
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.ConfigurationResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetConfiguration", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetConfiguration")
    @WebResult(name = "ConfigurationResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public ConfigurationResponse getConfiguration(
        @WebParam(name = "ConfigurationRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        Object parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

    /**
     * Gets latest mappings for angle differences and power corridors
     * 
     * @param parameters
     * @return
     *     returns com.eterra._public.services.data.datatypes.MappingsResponse
     * @throws InvalidParametersFault
     * @throws InternalServerFault
     */
    @WebMethod(operationName = "GetMappings", action = "http://www.eterra.com/public/services/data/historicaltrendprovider/GetMappings")
    @WebResult(name = "MappingsResponse", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
    public MappingsResponse getMappings(
        @WebParam(name = "MappingsRequest", targetNamespace = "http://www.eterra.com/public/services/data/dataTypes", partName = "parameters")
        Object parameters)
        throws InternalServerFault, InvalidParametersFault
    ;

}
