
package com.eterra._public.services.data.historicaltrendprovider;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HistoricalTrendProvider", targetNamespace = "http://www.eterra.com/public/services/data/historicaltrendprovider", wsdlLocation = "file:/C:/Users/Nagasudhir/Documents/PMU%20Projects/wei/HistoricalTrendProvider.wsdl")
public class HistoricalTrendProvider_Service
    extends Service
{

    private final static URL HISTORICALTRENDPROVIDER_WSDL_LOCATION;
    private final static WebServiceException HISTORICALTRENDPROVIDER_EXCEPTION;
    private final static QName HISTORICALTRENDPROVIDER_QNAME = new QName("http://www.eterra.com/public/services/data/historicaltrendprovider", "HistoricalTrendProvider");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Nagasudhir/Documents/PMU%20Projects/wei/HistoricalTrendProvider.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISTORICALTRENDPROVIDER_WSDL_LOCATION = url;
        HISTORICALTRENDPROVIDER_EXCEPTION = e;
    }

    public HistoricalTrendProvider_Service() {
        super(__getWsdlLocation(), HISTORICALTRENDPROVIDER_QNAME);
    }

    public HistoricalTrendProvider_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISTORICALTRENDPROVIDER_QNAME, features);
    }

    public HistoricalTrendProvider_Service(URL wsdlLocation) {
        super(wsdlLocation, HISTORICALTRENDPROVIDER_QNAME);
    }

    public HistoricalTrendProvider_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISTORICALTRENDPROVIDER_QNAME, features);
    }

    public HistoricalTrendProvider_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HistoricalTrendProvider_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HistoricalTrendProvider
     */
    @WebEndpoint(name = "HistoricalTrendProvider12")
    public HistoricalTrendProvider getHistoricalTrendProvider12() {
        return super.getPort(new QName("http://www.eterra.com/public/services/data/historicaltrendprovider", "HistoricalTrendProvider12"), HistoricalTrendProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HistoricalTrendProvider
     */
    @WebEndpoint(name = "HistoricalTrendProvider12")
    public HistoricalTrendProvider getHistoricalTrendProvider12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.eterra.com/public/services/data/historicaltrendprovider", "HistoricalTrendProvider12"), HistoricalTrendProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISTORICALTRENDPROVIDER_EXCEPTION!= null) {
            throw HISTORICALTRENDPROVIDER_EXCEPTION;
        }
        return HISTORICALTRENDPROVIDER_WSDL_LOCATION;
    }

}
